version: "3"
services:
  server:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - passwordapi
  passwordapi:
    image: nicopaez/password-api
    deploy:
      replicas: 2
    expose:
      - "3000"
