version: "3"
services:
  server:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - passwordapi_1
      - passwordapi_2
  passwordapi_1:
    image: nicopaez/password-api
    ports:
      - "3001:3000"
  passwordapi_2:
    image: nicopaez/password-api
    ports:
      - "3002:3000"
